export const scarityVal = {
  limited: 1,
  rare: 2,
  superRare: 3,
  unique: 4,
};

export const positionVal = {
  centreForward: 1,
  attackingMidfielder: 2,
  centreBack: 3,
  goalKeeper: 4,
  centreMidfielder: 5,
};

export const saleTypeVal = {
  bundles: 1,
  cards: 2,
};

export const scarity = [
  {
    id: 1,
    name: "Limited",
    value: 1,
    scarity: 1,
    cateName: "scarity",
  },
  {
    id: 2,
    name: "Rare",
    value: 2,
    scarity: 2,
    cateName: "scarity",
  },
  {
    id: 3,
    name: "Super Rare",
    value: 3,
    scarity: 3,
    cateName: "scarity",
  },
  {
    id: 4,
    name: "Unique",
    value: 4,
    scarity: 4,
    cateName: "scarity",
  },
];

export const position = [
  {
    id: 1,
    name: "Centre Forward",
    value: 1,
    position: 1,
    cateName: "position",
  },
  {
    id: 2,
    name: "Attacking Midfielder",
    value: 2,
    cateName: "position",
    position: 2,
  },
  {
    id: 3,
    name: "Centre Back",
    value: 3,
    cateName: "position",
    position: 3,
  },
  {
    id: 4,
    name: "Goal Keeper",
    value: 4,
    cateName: "position",
    position: 4,
  },
  {
    id: 5,
    name: "Centre Midfielder",
    value: 5,
    cateName: "position",
    position: 5,
  },
];

export const saleType = [
  {
    id: 1,
    name: "Bundles",
    value: 1,
    cateName: "saleType",
    saleType: 1,
  },
  {
    id: 2,
    name: "Cards",
    value: 2,
    cateName: "saleType",
    saleType: 2,
  },
];

export const playerListItems = [
  {
    playerName: "Haaland",
    scarity: scarityVal.limited,
    position: positionVal.attackingMidfielder,
    saleType: saleTypeVal.cards,
    img: "/images/market/haaland.png",
    value: "0018",
    stats: 86,
  },
  {
    playerName: "Messi",
    scarity: scarityVal.unique,
    position: positionVal.centreForward,
    saleType: saleTypeVal.cards,
    img: "/images/market/messi.png",
    value: "0018",
    stats: 90,
  },
  {
    playerName: "Mbappe",
    scarity: scarityVal.rare,
    position: positionVal.attackingMidfielder,
    saleType: saleTypeVal.cards,
    img: "/images/market/mbappe.png",
    value: "0018",
    stats: 90,
  },
  {
    playerName: "Kimmich",
    scarity: scarityVal.limited,
    position: positionVal.attackingMidfielder,
    saleType: saleTypeVal.bundles,
    img: "/images/market/kimmich.png",
    value: "0018",
    stats: 85,
  },
  {
    playerName: "Pogba",
    scarity: scarityVal.limited,
    position: positionVal.centreMidfielder,
    saleType: saleTypeVal.cards,
    img: "/images/market/pogba.png",
    value: "0018",
    stats: 88,
  },
  {
    playerName: "Ronaldo",
    scarity: scarityVal.unique,
    position: positionVal.centreBack,
    saleType: saleTypeVal.cards,
    img: "/images/market/ronaldo.png",
    value: "0018",
    stats: 94,
  },
  {
    playerName: "Pedri",
    scarity: scarityVal.rare,
    position: positionVal.centreMidfielder,
    saleType: saleTypeVal.bundles,
    img: "/images/market/pedri.png",
    value: "0018",
    stats: 83,
  },
  {
    playerName: "Neymar",
    scarity: scarityVal.unique,
    position: positionVal.centreBack,
    saleType: saleTypeVal.bundles,
    img: "/images/market/neymar.png",
    value: "0018",
    stats: 92,
  },
  {
    playerName: "Lewan",
    scarity: scarityVal.superRare,
    position: positionVal.attackingMidfielder,
    saleType: saleTypeVal.cards,
    img: "/images/market/lewan.png",
    value: "0018",
    stats: 90,
  },
  {
    playerName: "Nkunku",
    scarity: scarityVal.rare,
    position: positionVal.centreForward,
    saleType: saleTypeVal.bundles,
    img: "/images/market/nkunku.png",
    value: "0018",
    stats: 84,
  },
  {
    playerName: "Neuer",
    scarity: scarityVal.limited,
    position: positionVal.goalKeeper,
    saleType: saleTypeVal.bundles,
    img: "/images/market/neuer.png",
    value: "0018",
    stats: 91,
  },
  {
    playerName: "Benzema",
    scarity: scarityVal.superRare,
    position: positionVal.attackingMidfielder,
    saleType: saleTypeVal.cards,
    img: "/images/market/benzema.png",
    value: "0018",
    stats: 90,
  },
  {
    playerName: "Muller",
    scarity: scarityVal.superRare,
    position: positionVal.attackingMidfielder,
    saleType: saleTypeVal.cards,
    img: "/images/market/muller.png",
    value: "0018",
    stats: 90,
  },
  {
    playerName: "Ansu Fati",
    scarity: scarityVal.rare,
    position: positionVal.attackingMidfielder,
    saleType: saleTypeVal.bundles,
    img: "/images/market/fati.png",
    value: "0018",
    stats: 87,
  },
];
